import { BRAND } from './site'

export const SEO_KEYWORD_GROUPS = {
  cuteBrand: [
    'cute pokemon cards for sale',
    'pink pokemon card collection',
    'kawaii pokemon cards',
    'aesthetic pokemon card binder',
    'pastel fairy type cards',
    'adorable baby shiny pokemon',
    'cute pokemon cards',
    'girly pokemon cards',
    'cute pokemon tcg shop',
  ],
  speciesMoats: [
    'sylveon card shop',
    'mimikyu illustration rare',
    'maushold family cards',
    'eevee evolution full arts',
    'jigglypuff reverse holos',
    'togepi baby shinies',
    'espurr card collection',
    'jirachi star cards',
    'gardevoir art rare cards',
    'milotic beautiful pokemon card',
    'pumpkaboo halloween pokemon cards',
    'greavard ghost dog pokemon card',
    'eeveelution collector cards',
  ],
  pinkPalace: [
    'pink pokemon cards',
    'sylveon collection',
    'pastel tcg',
    'fairy pokemon card binder',
  ],
  cottagecoreAndFloral: [
    'floral pokemon cards',
    'cottagecore pokemon cards',
    'plant pokemon cards',
    'comfey cards',
    'shaymin land forme cards',
  ],
  spaceAndDreams: [
    'jirachi cards',
    'starry pokemon cards',
    'cosmog collection',
    'dreamy pokemon cards',
  ],
  cozyAndSoft: [
    'fluffy pokemon',
    'teddiursa cards',
    'cozy card binder',
    'soft aesthetic pokemon cards',
  ],
  babies: ['baby pokemon cards', 'actual baby pokemon cards', 'baby shiny pokemon'],
  tinyAndAdorable: [
    'tiny cute pokemon cards',
    'small adorable pokemon cards',
    'tiny pokemon card collection',
  ],
  foodAndSweetTreats: [
    'dessert pokemon cards',
    'food pokemon cards',
    'sweet treats pokemon cards',
    'cute bakery pokemon cards',
  ],
  dogs: ['dog pokemon cards', 'puppy pokemon cards', 'cute dog pokemon collection'],
  cats: ['cat pokemon cards', 'kitten pokemon cards', 'cute cat pokemon collection'],
  bunnies: ['bunny pokemon cards', 'rabbit pokemon cards', 'cute bunny pokemon collection'],
  mice: ['mouse pokemon cards', 'cute mice pokemon cards', 'pikachu clone pokemon cards'],
  allOtherAnimals: [
    'penguin pokemon cards',
    'seal pokemon cards',
    'giraffe pokemon cards',
    'cow pokemon cards',
    'bear pokemon cards',
    'animal pokemon collection',
  ],
  elegantAndFeminine: [
    'elegant pokemon cards',
    'feminine pokemon card collection',
    'pokemon special illustration rare',
  ],
  spookyCute: ['spooky cute pokemon cards', 'ghost pokemon cute collection', 'mimikyu fan cards'],
  eeveelutions: [
    'eeveelution cards',
    'eevee evolution cards',
    'sylveon espeon glaceon leafeon cards',
  ],
  rarity: [
    'Scarlet & Violet Illustration Rare cards',
    'Art Rare pokemon collection',
    'Japanese waifu cards',
    'CHV (Chinese) pokemon cards',
    'Special Illustration Rare (SIR) price guide',
  ],
  languages: ['english pokemon cards', 'japanese pokemon cards', 'chinese pokemon cards'],
  collectors: [
    'pokemon card shop',
    'pokemon card collector',
    'pokemon tcg puerto rico',
    'pokemon card live shopping',
  ],
  blog: ['pokemon card blog', 'pokemon tcg updates', 'pokemon collecting tips'],
} as const

export type SpeciesCollectionSlug =
  | 'pink-brigade'
  | 'babies'
  | 'tiny-and-adorable'
  | 'food-and-sweet-treats'
  | 'cottagecore-and-floral'
  | 'dogs'
  | 'cats'
  | 'bunny'
  | 'mice'
  | 'all-other-animals'
  | 'dreamy-and-ethereal'
  | 'pink-pastel-icons'
  | 'elegant-and-feminine'
  | 'spooky-cute'
  | 'eeveelution-core'

export type SpeciesKeywordConfig = {
  slug: string
  name: string
  titleName?: string
  collection: SpeciesCollectionSlug
  extraCollections?: SpeciesCollectionSlug[]
  translations: string[]
  relatedKeywords: string[]
  relatedEntities?: string[]
  /** Primary Pokémon types from PokéAPI (e.g. ["Fairy"], ["Ghost", "Fairy"]) */
  types?: string[]
  /** Pokédex generation number the species was introduced in (1–9) */
  generation?: number
}

type SpeciesSeoConfigInput = {
  siteName?: string
  includeKeywordGroups?: boolean
  customKeywords?: string[]
}

type PostKeywordConfigInput = {
  title: string
  tags?: string[]
  species?: string[]
  keywords?: string[]
}

export const SPECIES_COLLECTIONS = {
  'pink-brigade': {
    slug: 'pink-brigade',
    title: 'The Pink Brigade',
    description: 'Pink and pastel favorites that fit the Pink Binder brand.',
    featuredSpecies: ['Clefairy', 'Sylveon', 'Slowpoke', 'Jigglypuff', 'Eevee'],
  },
  babies: {
    slug: 'babies',
    title: 'Babies',
    description: 'Official baby Pokémon only, centered on the cutest pre-evolution collectors.',
    featuredSpecies: ['Cleffa', 'Togepi', 'Pichu', 'Azurill', 'Riolu'],
  },
  'tiny-and-adorable': {
    slug: 'tiny-and-adorable',
    title: 'Tiny & Adorable',
    description: 'Small, playful, and extra-cute Pokémon for tiny binder themes.',
    featuredSpecies: ['Maushold', 'Pawmi', 'Cutiefly', 'Piplup', 'Snom'],
  },
  'food-and-sweet-treats': {
    slug: 'food-and-sweet-treats',
    title: 'Food & Sweet Treats',
    description: 'Dessert, bakery, candy, tea, and snack-inspired Pokémon collectors love.',
    featuredSpecies: ['Milcery', 'Alcremie', 'Swirlix', 'Vanillite', 'Fidough'],
  },
  'cottagecore-and-floral': {
    slug: 'cottagecore-and-floral',
    title: 'Cottagecore & Floral',
    description: 'Soft floral, meadow, orchard, and plant-based Pokémon with cottagecore appeal.',
    featuredSpecies: ['Shaymin', 'Comfey', 'Flabébé', 'Petilil', 'Smoliv'],
  },
  dogs: {
    slug: 'dogs',
    title: 'Dogs & Canines',
    description:
      'Dog, wolf, and other canine-inspired Pokémon for collectors who love the full canine family.',
    featuredSpecies: ['Growlithe', 'Arcanine', 'Yamper', 'Boltund', 'Rockruff'],
  },
  cats: {
    slug: 'cats',
    title: 'Cats & Felines',
    description: 'Cat, kitten, and big-cat inspired Pokémon for feline-focused collection themes.',
    featuredSpecies: ['Meowth', 'Persian', 'Skitty', 'Sprigatito', 'Litten'],
  },
  bunny: {
    slug: 'bunny',
    title: 'Rabbits & Bunnies',
    description:
      'Rabbit and bunny-inspired Pokémon from playful classics to battle-ready evolutions.',
    featuredSpecies: ['Buneary', 'Lopunny', 'Scorbunny', 'Bunnelby', 'Diggersby'],
  },
  mice: {
    slug: 'mice',
    title: 'Mice & Rodents',
    description:
      'Mouse and rodent-inspired Pokémon, including mascots, pika-clones, and chinchilla lines.',
    featuredSpecies: ['Pichu', 'Pikachu', 'Raichu', 'Dedenne', 'Cinccino'],
  },
  'all-other-animals': {
    slug: 'all-other-animals',
    title: 'Other Animal Friends',
    description:
      'A broad animal mix beyond cats, dogs, rabbits, and rodents: penguins, seals, bears, sheep, and more.',
    featuredSpecies: ['Piplup', 'Spheal', 'Teddiursa', 'Wooloo', 'Miltank'],
  },
  'dreamy-and-ethereal': {
    slug: 'dreamy-and-ethereal',
    title: 'Dreamy & Ethereal',
    description: 'Soft, magical, and collector-focused Pokémon species hubs.',
    featuredSpecies: ['Jirachi', 'Cresselia', 'Mew', 'Mimikyu', 'Espurr'],
  },
  'pink-pastel-icons': {
    slug: 'pink-pastel-icons',
    title: 'Pink & Pastel Icons',
    description: 'Highest-volume pink, pastel, fairy, and heart-themed Pokémon collections.',
    featuredSpecies: ['Sylveon', 'Mew', 'Jigglypuff', 'Clefairy', 'Hatterene'],
  },
  'elegant-and-feminine': {
    slug: 'elegant-and-feminine',
    title: 'Elegant & Feminine Meta',
    description: 'Elegant, refined species tied to premium AR and SIR collector demand.',
    featuredSpecies: ['Gardevoir', 'Milotic', 'Altaria', 'Diancie', 'Cresselia'],
  },
  'spooky-cute': {
    slug: 'spooky-cute',
    title: 'Spooky-Cute Niche',
    description: 'Ghost and psychic favorites with loyal spooky-cute fanbases.',
    featuredSpecies: ['Mimikyu', 'Espurr', 'Meowstic', 'Misdreavus', 'Pumpkaboo'],
  },
  'eeveelution-core': {
    slug: 'eeveelution-core',
    title: 'Eeveelution Core',
    description: 'Mandatory Eevee and top Eeveelution species for cute collector traffic.',
    featuredSpecies: ['Eevee', 'Sylveon', 'Espeon', 'Glaceon', 'Leafeon'],
  },
} as const satisfies Record<
  SpeciesCollectionSlug,
  {
    slug: SpeciesCollectionSlug
    title: string
    description: string
    featuredSpecies: string[]
  }
>

const SPECIES_COLLECTION_KEYWORDS: Record<SpeciesCollectionSlug, string[]> = {
  'pink-brigade': [...SEO_KEYWORD_GROUPS.cuteBrand, ...SEO_KEYWORD_GROUPS.pinkPalace],
  babies: [...SEO_KEYWORD_GROUPS.cuteBrand, ...SEO_KEYWORD_GROUPS.babies],
  'tiny-and-adorable': [...SEO_KEYWORD_GROUPS.cuteBrand, ...SEO_KEYWORD_GROUPS.tinyAndAdorable],
  'food-and-sweet-treats': [
    ...SEO_KEYWORD_GROUPS.cuteBrand,
    ...SEO_KEYWORD_GROUPS.foodAndSweetTreats,
  ],
  'cottagecore-and-floral': [
    ...SEO_KEYWORD_GROUPS.cuteBrand,
    ...SEO_KEYWORD_GROUPS.cottagecoreAndFloral,
  ],
  dogs: [...SEO_KEYWORD_GROUPS.cuteBrand, ...SEO_KEYWORD_GROUPS.dogs],
  cats: [...SEO_KEYWORD_GROUPS.cuteBrand, ...SEO_KEYWORD_GROUPS.cats],
  bunny: [...SEO_KEYWORD_GROUPS.cuteBrand, ...SEO_KEYWORD_GROUPS.bunnies],
  mice: [...SEO_KEYWORD_GROUPS.cuteBrand, ...SEO_KEYWORD_GROUPS.mice],
  'all-other-animals': [...SEO_KEYWORD_GROUPS.cuteBrand, ...SEO_KEYWORD_GROUPS.allOtherAnimals],
  'dreamy-and-ethereal': [...SEO_KEYWORD_GROUPS.cuteBrand, ...SEO_KEYWORD_GROUPS.spaceAndDreams],
  'pink-pastel-icons': [...SEO_KEYWORD_GROUPS.cuteBrand, ...SEO_KEYWORD_GROUPS.pinkPalace],
  'elegant-and-feminine': [
    ...SEO_KEYWORD_GROUPS.cuteBrand,
    ...SEO_KEYWORD_GROUPS.elegantAndFeminine,
  ],
  'spooky-cute': [...SEO_KEYWORD_GROUPS.cuteBrand, ...SEO_KEYWORD_GROUPS.spookyCute],
  'eeveelution-core': [...SEO_KEYWORD_GROUPS.cuteBrand, ...SEO_KEYWORD_GROUPS.eeveelutions],
}

const SPECIES_KEYWORD_SEEDS: SpeciesKeywordConfig[] = [
  // ─── Eeveelution Core ───────────────────────────────────────────────────────
  {
    slug: 'eevee',
    name: 'Eevee',
    titleName: 'Eevee & Evolution',
    collection: 'eeveelution-core',
    extraCollections: ['all-other-animals'],
    translations: ['イーブイ', '伊布'],
    relatedKeywords: ['eevee evolution full arts', 'cute eevee cards'],
    relatedEntities: [
      'Sylveon',
      'Espeon',
      'Vaporeon',
      'Flareon',
      'Jolteon',
      'Umbreon',
      'Glaceon',
      'Leafeon',
    ],
    types: ['Normal'],
    generation: 1,
  },
  {
    slug: 'sylveon',
    name: 'Sylveon',
    titleName: 'Sylveon & Eeveelution',
    collection: 'eeveelution-core',
    translations: ['ニンフィア', '仙子伊布'],
    relatedKeywords: ['sylveon card shop', 'eeveelution cute cards', 'fairy type sylveon cards'],
    relatedEntities: [
      'Eevee',
      'Espeon',
      'Glaceon',
      'Vaporeon',
      'Flareon',
      'Jolteon',
      'Umbreon',
      'Leafeon',
    ],
    types: ['Fairy'],
    generation: 6,
  },
  {
    slug: 'espeon',
    name: 'Espeon',
    collection: 'eeveelution-core',
    translations: ['エーフィ', '太阳伊布'],
    relatedKeywords: ['espeon cards', 'psychic eeveelution cards'],
    relatedEntities: [
      'Eevee',
      'Sylveon',
      'Glaceon',
      'Vaporeon',
      'Flareon',
      'Jolteon',
      'Umbreon',
      'Leafeon',
    ],
    types: ['Psychic'],
    generation: 2,
  },
  {
    slug: 'glaceon',
    name: 'Glaceon',
    collection: 'eeveelution-core',
    translations: ['グレイシア', '冰伊布'],
    relatedKeywords: ['glaceon cards', 'elegant blue pokemon cards'],
    relatedEntities: [
      'Eevee',
      'Leafeon',
      'Sylveon',
      'Espeon',
      'Vaporeon',
      'Flareon',
      'Jolteon',
      'Umbreon',
    ],
    types: ['Ice'],
    generation: 4,
  },
  {
    slug: 'leafeon',
    name: 'Leafeon',
    collection: 'eeveelution-core',
    translations: ['リーフィア', '叶伊布'],
    relatedKeywords: ['leafeon cards', 'leafeon art rare cards'],
    relatedEntities: [
      'Eevee',
      'Glaceon',
      'Sylveon',
      'Espeon',
      'Vaporeon',
      'Flareon',
      'Jolteon',
      'Umbreon',
    ],
    types: ['Grass'],
    generation: 4,
  },
  {
    slug: 'vaporeon',
    name: 'Vaporeon',
    collection: 'eeveelution-core',
    translations: ['シャワーズ', '水伊布'],
    relatedKeywords: ['vaporeon cards', 'water eeveelution cards'],
    relatedEntities: [
      'Eevee',
      'Glaceon',
      'Sylveon',
      'Espeon',
      'Flareon',
      'Jolteon',
      'Umbreon',
      'Leafeon',
    ],
    types: ['Water'],
    generation: 1,
  },
  {
    slug: 'flareon',
    name: 'Flareon',
    collection: 'eeveelution-core',
    translations: ['ブースター', '火伊布'],
    relatedKeywords: ['flareon cards', 'fire eeveelution cards'],
    relatedEntities: [
      'Eevee',
      'Espeon',
      'Sylveon',
      'Glaceon',
      'Vaporeon',
      'Jolteon',
      'Umbreon',
      'Leafeon',
    ],
    types: ['Fire'],
    generation: 1,
  },
  {
    slug: 'jolteon',
    name: 'Jolteon',
    collection: 'eeveelution-core',
    translations: ['サンダース', '雷伊布'],
    relatedKeywords: ['jolteon cards', 'electric eeveelution cards'],
    relatedEntities: [
      'Eevee',
      'Espeon',
      'Sylveon',
      'Glaceon',
      'Vaporeon',
      'Flareon',
      'Umbreon',
      'Leafeon',
    ],
    types: ['Electric'],
    generation: 1,
  },
  {
    slug: 'umbreon',
    name: 'Umbreon',
    collection: 'eeveelution-core',
    translations: ['ブラッキー', '月亮伊布'],
    relatedKeywords: ['umbreon cards', 'umbreon moonlight collection', 'dark eeveelution cards'],
    relatedEntities: [
      'Eevee',
      'Espeon',
      'Sylveon',
      'Glaceon',
      'Vaporeon',
      'Flareon',
      'Jolteon',
      'Leafeon',
    ],
    types: ['Dark'],
    generation: 2,
  },
  // ─── Pink & Pastel Icons ─────────────────────────────────────────────────────
  {
    slug: 'jigglypuff',
    name: 'Jigglypuff',
    collection: 'pink-pastel-icons',
    translations: ['プリン', '胖丁'],
    relatedKeywords: ['jigglypuff reverse holos', 'cute jigglypuff cards'],
    relatedEntities: ['Clefairy', 'Sylveon', 'Wigglytuff'],
    types: ['Normal', 'Fairy'],
    generation: 1,
  },
  {
    slug: 'wigglytuff',
    name: 'Wigglytuff',
    collection: 'pink-pastel-icons',
    translations: [],
    relatedKeywords: ['wigglytuff cute cards', 'pink wigglytuff pokemon cards'],
    relatedEntities: ['Jigglypuff', 'Clefable', 'Igglybuff'],
    types: ['Normal', 'Fairy'],
    generation: 1,
  },
  {
    slug: 'clefairy',
    name: 'Clefairy',
    collection: 'pink-pastel-icons',
    translations: ['ピッピ', '皮皮'],
    relatedKeywords: ['clefairy card collection', 'pastel clefairy cards'],
    relatedEntities: ['Clefable', 'Cleffa', 'Sylveon'],
    types: ['Normal', 'Fairy'],
    generation: 1,
  },
  {
    slug: 'clefable',
    name: 'Clefable',
    collection: 'pink-pastel-icons',
    translations: ['ピクシー', '皮可西'],
    relatedKeywords: ['clefable pokemon cards', 'cute clefable cards'],
    relatedEntities: ['Clefairy', 'Cleffa'],
    types: ['Normal', 'Fairy'],
    generation: 1,
  },
  {
    slug: 'mew',
    name: 'Mew',
    collection: 'pink-pastel-icons',
    extraCollections: ['cats'],
    translations: ['ミュウ', '梦幻'],
    relatedKeywords: ['mew bubble card', 'mew corocoro promo', 'cute mew cards'],
    relatedEntities: ['Jirachi', 'Cresselia'],
    types: ['Psychic'],
    generation: 1,
  },
  {
    slug: 'slowpoke',
    name: 'Slowpoke',
    collection: 'pink-pastel-icons',
    translations: ['ヤドン', '呆呆兽'],
    relatedKeywords: ['slowpoke cute cards', 'derpy slowpoke collection'],
    relatedEntities: ['Mew', 'Sylveon'],
    types: ['Water', 'Psychic'],
    generation: 1,
  },
  {
    slug: 'chansey',
    name: 'Chansey',
    collection: 'pink-pastel-icons',
    translations: [],
    relatedKeywords: ['chansey pokemon cards', 'pink chansey cards'],
    relatedEntities: ['Blissey', 'Clefable'],
    types: ['Normal'],
    generation: 1,
  },
  {
    slug: 'blissey',
    name: 'Blissey',
    collection: 'pink-pastel-icons',
    translations: [],
    relatedKeywords: ['blissey pokemon cards', 'cute blissey card collection'],
    relatedEntities: ['Chansey', 'Happiny'],
    types: ['Normal'],
    generation: 2,
  },
  {
    slug: 'alomomola',
    name: 'Alomomola',
    collection: 'pink-pastel-icons',
    translations: [],
    relatedKeywords: ['alomomola card collection', 'heart shaped pokemon cards'],
    relatedEntities: ['Luvdisc', 'Mew'],
    types: ['Water'],
    generation: 5,
  },
  {
    slug: 'luvdisc',
    name: 'Luvdisc',
    collection: 'pink-pastel-icons',
    translations: [],
    relatedKeywords: ['luvdisc pokemon cards', 'heart pokemon card binder'],
    relatedEntities: ['Alomomola', 'Sylveon'],
    types: ['Water'],
    generation: 3,
  },
  {
    slug: 'hatenna',
    name: 'Hatenna',
    collection: 'pink-pastel-icons',
    translations: [],
    relatedKeywords: ['hatenna cards', 'cute hatenna pokemon card'],
    relatedEntities: ['Hattrem', 'Hatterene'],
    types: ['Psychic'],
    generation: 8,
  },
  {
    slug: 'hattrem',
    name: 'Hattrem',
    collection: 'pink-pastel-icons',
    translations: [],
    relatedKeywords: ['hattrem cards', 'pink psychic pokemon cards'],
    relatedEntities: ['Hatenna', 'Hatterene'],
    types: ['Psychic'],
    generation: 8,
  },
  {
    slug: 'hatterene',
    name: 'Hatterene',
    collection: 'pink-pastel-icons',
    translations: [],
    relatedKeywords: ['hatterene cards', 'cute witch pokemon cards'],
    relatedEntities: ['Hatenna', 'Hattrem'],
    types: ['Psychic', 'Fairy'],
    generation: 8,
  },
  {
    slug: 'milcery',
    name: 'Milcery',
    collection: 'food-and-sweet-treats',
    translations: [],
    relatedKeywords: ['milcery cards', 'dessert pokemon cards'],
    relatedEntities: ['Alcremie', 'Sylveon'],
    types: ['Fairy'],
    generation: 8,
  },
  {
    slug: 'alcremie',
    name: 'Alcremie',
    collection: 'food-and-sweet-treats',
    translations: [],
    relatedKeywords: ['alcremie cards', 'dessert aesthetic pokemon cards'],
    relatedEntities: ['Milcery', 'Sylveon'],
    types: ['Fairy'],
    generation: 8,
  },
  {
    slug: 'snubbull',
    name: 'Snubbull',
    collection: 'pink-pastel-icons',
    extraCollections: ['dogs'],
    translations: ['ブルー', '布鲁'],
    relatedKeywords: ['snubbull cards', 'pink bulldog pokemon cards'],
    relatedEntities: ['Granbull', 'Clefairy'],
    types: ['Fairy'],
    generation: 2,
  },
  {
    slug: 'granbull',
    name: 'Granbull',
    collection: 'pink-pastel-icons',
    extraCollections: ['dogs'],
    translations: [],
    relatedKeywords: ['granbull cards', 'pink fairy bulldog pokemon cards'],
    relatedEntities: ['Snubbull', 'Hatterene'],
    types: ['Fairy'],
    generation: 2,
  },
  {
    slug: 'marill',
    name: 'Marill',
    collection: 'pink-pastel-icons',
    extraCollections: ['mice', 'all-other-animals'],
    translations: ['マリル', '玛力露'],
    relatedKeywords: ['marill cards', 'blue fairy pokemon cards'],
    relatedEntities: ['Azumarill', 'Jigglypuff'],
    types: ['Water', 'Fairy'],
    generation: 2,
  },
  {
    slug: 'azumarill',
    name: 'Azumarill',
    collection: 'pink-pastel-icons',
    extraCollections: ['mice', 'all-other-animals'],
    translations: ['マリルリ', '玛力露丽'],
    relatedKeywords: ['azumarill cards', 'water fairy pokemon cards'],
    relatedEntities: ['Marill', 'Sylveon'],
    types: ['Water', 'Fairy'],
    generation: 2,
  },
  {
    slug: 'audino',
    name: 'Audino',
    collection: 'pink-pastel-icons',
    translations: ['タブンネ', '差不多娃娃'],
    relatedKeywords: ['audino cards', 'pink healer pokemon cards'],
    relatedEntities: ['Chansey', 'Clefairy'],
    types: ['Normal'],
    generation: 5,
  },
  {
    slug: 'spritzee',
    name: 'Spritzee',
    collection: 'pink-pastel-icons',
    translations: [],
    relatedKeywords: ['spritzee cards', 'pink perfume fairy pokemon cards'],
    relatedEntities: ['Aromatisse', 'Sylveon'],
    types: ['Fairy'],
    generation: 6,
  },
  {
    slug: 'aromatisse',
    name: 'Aromatisse',
    collection: 'pink-pastel-icons',
    translations: [],
    relatedKeywords: ['aromatisse cards', 'fairy pink pokemon cards'],
    relatedEntities: ['Spritzee', 'Sylveon'],
    types: ['Fairy'],
    generation: 6,
  },
  {
    slug: 'swirlix',
    name: 'Swirlix',
    collection: 'food-and-sweet-treats',
    translations: [],
    relatedKeywords: ['swirlix cards', 'cotton candy pokemon cards'],
    relatedEntities: ['Slurpuff', 'Milcery'],
    types: ['Fairy'],
    generation: 6,
  },
  {
    slug: 'slurpuff',
    name: 'Slurpuff',
    collection: 'food-and-sweet-treats',
    translations: [],
    relatedKeywords: ['slurpuff cards', 'dessert fairy pokemon cards'],
    relatedEntities: ['Swirlix', 'Alcremie'],
    types: ['Fairy'],
    generation: 6,
  },
  {
    slug: 'flabebe',
    name: 'Flabébé',
    collection: 'cottagecore-and-floral',
    translations: [],
    relatedKeywords: ['flabebe cards', 'tiny flower fairy pokemon cards'],
    relatedEntities: ['Floette', 'Florges'],
    types: ['Fairy'],
    generation: 6,
  },
  {
    slug: 'floette',
    name: 'Floette',
    collection: 'cottagecore-and-floral',
    translations: [],
    relatedKeywords: ['floette cards', 'flower fairy pokemon cards'],
    relatedEntities: ['Flabébé', 'Florges'],
    types: ['Fairy'],
    generation: 6,
  },
  {
    slug: 'florges',
    name: 'Florges',
    collection: 'cottagecore-and-floral',
    translations: [],
    relatedKeywords: ['florges cards', 'flower queen pokemon cards'],
    relatedEntities: ['Floette', 'Lilligant'],
    types: ['Fairy'],
    generation: 6,
  },
  // ─── Babies ─────────────────────────────────────────────────────────────────
  {
    slug: 'cleffa',
    name: 'Cleffa',
    collection: 'babies',
    translations: ['ピィ', '宝宝丁'],
    relatedKeywords: ['cleffa baby pokemon cards', 'cleffa shiny cards'],
    relatedEntities: ['Clefairy', 'Igglybuff'],
    types: ['Normal', 'Fairy'],
    generation: 2,
  },
  {
    slug: 'igglybuff',
    name: 'Igglybuff',
    collection: 'babies',
    translations: ['ププリン', '宝宝波'],
    relatedKeywords: ['igglybuff baby cards', 'igglybuff shiny cards'],
    relatedEntities: ['Jigglypuff', 'Cleffa'],
    types: ['Normal', 'Fairy'],
    generation: 2,
  },
  {
    slug: 'togepi',
    name: 'Togepi',
    collection: 'babies',
    translations: ['トゲピー', '波克比'],
    relatedKeywords: ['togepi baby shinies', 'cute togepi cards'],
    relatedEntities: ['Togetic', 'Togekiss'],
    types: ['Normal', 'Fairy'],
    generation: 2,
  },
  {
    slug: 'pichu',
    name: 'Pichu',
    collection: 'babies',
    extraCollections: ['mice'],
    translations: ['ピチュー', '皮丘'],
    relatedKeywords: ['pichu baby cards', 'pichu shiny cards'],
    relatedEntities: ['Pikachu', 'Dedenne'],
    types: ['Electric'],
    generation: 2,
  },
  {
    slug: 'happiny',
    name: 'Happiny',
    collection: 'babies',
    translations: ['ピンプク', '小福蛋'],
    relatedKeywords: ['happiny cards', 'baby chansey pokemon cards'],
    relatedEntities: ['Chansey', 'Cleffa'],
    types: ['Normal'],
    generation: 4,
  },
  {
    slug: 'tyrogue',
    name: 'Tyrogue',
    collection: 'babies',
    translations: [],
    relatedKeywords: ['tyrogue cards', 'baby fighting pokemon cards'],
    relatedEntities: ['Hitmonlee', 'Hitmonchan', 'Hitmontop'],
    types: ['Fighting'],
    generation: 2,
  },
  {
    slug: 'smoochum',
    name: 'Smoochum',
    collection: 'babies',
    translations: [],
    relatedKeywords: ['smoochum cards', 'baby psychic pokemon cards'],
    relatedEntities: ['Jynx', 'Cleffa'],
    types: ['Ice', 'Psychic'],
    generation: 2,
  },
  {
    slug: 'elekid',
    name: 'Elekid',
    collection: 'babies',
    translations: [],
    relatedKeywords: ['elekid cards', 'baby electric pokemon cards'],
    relatedEntities: ['Electabuzz', 'Pichu'],
    types: ['Electric'],
    generation: 2,
  },
  {
    slug: 'magby',
    name: 'Magby',
    collection: 'babies',
    translations: [],
    relatedKeywords: ['magby cards', 'baby fire pokemon cards'],
    relatedEntities: ['Magmar', 'Togepi'],
    types: ['Fire'],
    generation: 2,
  },
  {
    slug: 'azurill',
    name: 'Azurill',
    collection: 'babies',
    translations: [],
    relatedKeywords: ['azurill cards', 'baby water fairy pokemon cards'],
    relatedEntities: ['Marill', 'Pichu'],
    types: ['Normal', 'Fairy'],
    generation: 3,
  },
  {
    slug: 'wynaut',
    name: 'Wynaut',
    collection: 'babies',
    translations: [],
    relatedKeywords: ['wynaut cards', 'baby psychic pokemon cards'],
    relatedEntities: ['Wobbuffet', 'Cleffa'],
    types: ['Psychic'],
    generation: 3,
  },
  {
    slug: 'budew',
    name: 'Budew',
    collection: 'babies',
    translations: [],
    relatedKeywords: ['budew cards', 'baby grass pokemon cards'],
    relatedEntities: ['Roselia', 'Roserade'],
    types: ['Grass', 'Poison'],
    generation: 4,
  },
  {
    slug: 'chingling',
    name: 'Chingling',
    collection: 'babies',
    translations: [],
    relatedKeywords: ['chingling cards', 'baby bell pokemon cards'],
    relatedEntities: ['Chimecho', 'Cleffa'],
    types: ['Psychic'],
    generation: 4,
  },
  {
    slug: 'bonsly',
    name: 'Bonsly',
    collection: 'babies',
    translations: [],
    relatedKeywords: ['bonsly cards', 'baby bonsai pokemon cards'],
    relatedEntities: ['Sudowoodo', 'Budew'],
    types: ['Rock'],
    generation: 4,
  },
  {
    slug: 'mime-jr',
    name: 'Mime Jr.',
    collection: 'babies',
    translations: [],
    relatedKeywords: ['mime jr cards', 'baby mime pokemon cards'],
    relatedEntities: ['Mr. Mime', 'Cleffa'],
    types: ['Psychic', 'Fairy'],
    generation: 4,
  },
  {
    slug: 'munchlax',
    name: 'Munchlax',
    collection: 'babies',
    translations: [],
    relatedKeywords: ['munchlax cards', 'baby snorlax pokemon cards'],
    relatedEntities: ['Snorlax', 'Togepi'],
    types: ['Normal'],
    generation: 4,
  },
  {
    slug: 'mantyke',
    name: 'Mantyke',
    collection: 'babies',
    translations: [],
    relatedKeywords: ['mantyke cards', 'baby manta ray pokemon cards'],
    relatedEntities: ['Mantine', 'Azurill'],
    types: ['Water', 'Flying'],
    generation: 4,
  },
  {
    slug: 'riolu',
    name: 'Riolu',
    collection: 'babies',
    translations: [],
    relatedKeywords: ['riolu cards', 'baby aura pokemon cards'],
    relatedEntities: ['Lucario', 'Togepi'],
    types: ['Fighting'],
    generation: 4,
  },
  {
    slug: 'toxel',
    name: 'Toxel',
    collection: 'babies',
    translations: [],
    relatedKeywords: ['toxel cards', 'baby punk pokemon cards'],
    relatedEntities: ['Toxtricity', 'Pichu'],
    types: ['Electric', 'Poison'],
    generation: 8,
  },
  {
    slug: 'hitmonlee',
    name: 'Hitmonlee',
    collection: 'babies',
    translations: [],
    relatedKeywords: ['hitmonlee cards', 'kicking pokemon cards'],
    relatedEntities: ['Tyrogue', 'Hitmonchan', 'Hitmontop'],
    types: ['Fighting'],
    generation: 1,
  },
  {
    slug: 'hitmonchan',
    name: 'Hitmonchan',
    collection: 'babies',
    translations: [],
    relatedKeywords: ['hitmonchan cards', 'boxing pokemon cards'],
    relatedEntities: ['Tyrogue', 'Hitmonlee', 'Hitmontop'],
    types: ['Fighting'],
    generation: 1,
  },
  {
    slug: 'hitmontop',
    name: 'Hitmontop',
    collection: 'babies',
    translations: [],
    relatedKeywords: ['hitmontop cards', 'spinning pokemon cards'],
    relatedEntities: ['Tyrogue', 'Hitmonlee', 'Hitmonchan'],
    types: ['Fighting'],
    generation: 2,
  },
  {
    slug: 'jynx',
    name: 'Jynx',
    collection: 'babies',
    translations: [],
    relatedKeywords: ['jynx cards', 'ice psychic pokemon cards'],
    relatedEntities: ['Smoochum', 'Mr. Mime'],
    types: ['Ice', 'Psychic'],
    generation: 1,
  },
  {
    slug: 'electabuzz',
    name: 'Electabuzz',
    collection: 'babies',
    translations: [],
    relatedKeywords: ['electabuzz cards', 'electric pokemon cards'],
    relatedEntities: ['Elekid', 'Magmar'],
    types: ['Electric'],
    generation: 1,
  },
  {
    slug: 'magmar',
    name: 'Magmar',
    collection: 'babies',
    translations: [],
    relatedKeywords: ['magmar cards', 'fire pokemon cards'],
    relatedEntities: ['Magby', 'Electabuzz'],
    types: ['Fire'],
    generation: 1,
  },
  {
    slug: 'wobbuffet',
    name: 'Wobbuffet',
    collection: 'babies',
    translations: [],
    relatedKeywords: ['wobbuffet cards', 'counter pokemon cards'],
    relatedEntities: ['Wynaut', 'Mr. Mime'],
    types: ['Psychic'],
    generation: 2,
  },
  {
    slug: 'chimecho',
    name: 'Chimecho',
    collection: 'babies',
    translations: [],
    relatedKeywords: ['chimecho cards', 'wind chime pokemon cards'],
    relatedEntities: ['Chingling', 'Wobbuffet'],
    types: ['Psychic'],
    generation: 3,
  },
  {
    slug: 'sudowoodo',
    name: 'Sudowoodo',
    collection: 'babies',
    translations: [],
    relatedKeywords: ['sudowoodo cards', 'fake tree pokemon cards'],
    relatedEntities: ['Bonsly', 'Oddish'],
    types: ['Rock'],
    generation: 2,
  },
  {
    slug: 'mr-mime',
    name: 'Mr. Mime',
    collection: 'babies',
    translations: [],
    relatedKeywords: ['mr mime cards', 'mime pokemon cards'],
    relatedEntities: ['Mime Jr.', 'Jynx'],
    types: ['Psychic', 'Fairy'],
    generation: 1,
  },
  {
    slug: 'snorlax',
    name: 'Snorlax',
    collection: 'babies',
    translations: [],
    relatedKeywords: ['snorlax cards', 'sleeping pokemon cards'],
    relatedEntities: ['Munchlax', 'Teddiursa'],
    types: ['Normal'],
    generation: 1,
  },
  {
    slug: 'mantine',
    name: 'Mantine',
    collection: 'babies',
    translations: [],
    relatedKeywords: ['mantine cards', 'manta ray pokemon cards'],
    relatedEntities: ['Mantyke', 'Spheal'],
    types: ['Water', 'Flying'],
    generation: 2,
  },
  {
    slug: 'lucario',
    name: 'Lucario',
    collection: 'babies',
    translations: [],
    relatedKeywords: ['lucario cards', 'aura pokemon cards'],
    relatedEntities: ['Riolu', 'Togepi'],
    types: ['Fighting', 'Steel'],
    generation: 4,
  },
  {
    slug: 'toxtricity',
    name: 'Toxtricity',
    collection: 'babies',
    translations: [],
    relatedKeywords: ['toxtricity cards', 'punk pokemon cards'],
    relatedEntities: ['Toxel', 'Pichu'],
    types: ['Electric', 'Poison'],
    generation: 8,
  },
  // ─── Tiny & Adorable ─────────────────────────────────────────────────────────
  {
    slug: 'togetic',
    name: 'Togetic',
    collection: 'tiny-and-adorable',
    translations: ['トゲチック', '波克基古'],
    relatedKeywords: ['togetic cards', 'cute togetic pokemon cards'],
    relatedEntities: ['Togepi', 'Togekiss'],
    types: ['Normal', 'Fairy'],
    generation: 2,
  },
  {
    slug: 'teddiursa',
    name: 'Teddiursa',
    collection: 'tiny-and-adorable',
    extraCollections: ['all-other-animals'],
    translations: ['ヒメグマ', '熊宝宝'],
    relatedKeywords: ['teddiursa cards', 'teddy bear pokemon cards'],
    relatedEntities: ['Skitty', 'Pichu'],
    types: ['Normal'],
    generation: 2,
  },
  {
    slug: 'buneary',
    name: 'Buneary',
    collection: 'tiny-and-adorable',
    extraCollections: ['bunny'],
    translations: ['ミミロル', '卷卷耳'],
    relatedKeywords: ['buneary cards', 'cute bunny pokemon cards'],
    relatedEntities: ['Lopunny', 'Minccino'],
    types: ['Normal'],
    generation: 4,
  },
  {
    slug: 'cutiefly',
    name: 'Cutiefly',
    collection: 'tiny-and-adorable',
    translations: [],
    relatedKeywords: ['cutiefly cards', 'tiny cute pokemon cards'],
    relatedEntities: ['Ribombee', 'Togepi'],
    types: ['Bug', 'Fairy'],
    generation: 7,
  },
  {
    slug: 'ribombee',
    name: 'Ribombee',
    collection: 'tiny-and-adorable',
    translations: [],
    relatedKeywords: ['ribombee cards', 'cute fairy bug pokemon cards'],
    relatedEntities: ['Cutiefly', 'Sylveon'],
    types: ['Bug', 'Fairy'],
    generation: 7,
  },
  {
    slug: 'tandemaus',
    name: 'Tandemaus',
    collection: 'tiny-and-adorable',
    extraCollections: ['mice'],
    translations: [],
    relatedKeywords: ['tandemaus cards', 'cute family mouse pokemon cards'],
    relatedEntities: ['Maushold', 'Pawmi', 'Dedenne'],
    types: ['Normal'],
    generation: 9,
  },
  {
    slug: 'maushold',
    name: 'Maushold',
    collection: 'tiny-and-adorable',
    extraCollections: ['mice'],
    translations: ['イッカネズミ', '一家鼠'],
    relatedKeywords: ['maushold family cards', 'cute maushold cards'],
    relatedEntities: ['Tandemaus', 'Pawmi', 'Dedenne'],
    types: ['Normal'],
    generation: 9,
  },
  {
    slug: 'dedenne',
    name: 'Dedenne',
    collection: 'tiny-and-adorable',
    extraCollections: ['mice'],
    translations: ['デデンネ', '咚咚鼠'],
    relatedKeywords: ['dedenne cards', 'cute mouse electric pokemon cards', 'pikachu clone cards'],
    relatedEntities: ['Pichu', 'Tandemaus', 'Maushold', 'Pawmi'],
    types: ['Electric', 'Fairy'],
    generation: 6,
  },
  {
    slug: 'pawmi',
    name: 'Pawmi',
    collection: 'tiny-and-adorable',
    extraCollections: ['mice'],
    translations: ['パモ', '布拨'],
    relatedKeywords: ['pawmi cards', 'cute pawmi card collection'],
    relatedEntities: ['Pawmo', 'Pawmot'],
    types: ['Electric'],
    generation: 9,
  },
  {
    slug: 'pawmo',
    name: 'Pawmo',
    collection: 'tiny-and-adorable',
    translations: [],
    relatedKeywords: ['pawmo cards', 'pawmo evolution cards'],
    relatedEntities: ['Pawmi', 'Pawmot'],
    types: ['Electric', 'Fighting'],
    generation: 9,
  },
  {
    slug: 'pawmot',
    name: 'Pawmot',
    collection: 'tiny-and-adorable',
    translations: [],
    relatedKeywords: ['pawmot cards', 'pawmi evolution line cards'],
    relatedEntities: ['Pawmi', 'Pawmo'],
    types: ['Electric', 'Fighting'],
    generation: 9,
  },
  {
    slug: 'minccino',
    name: 'Minccino',
    collection: 'tiny-and-adorable',
    extraCollections: ['mice'],
    translations: [],
    relatedKeywords: ['minccino cards', 'fluffy pokemon cards'],
    relatedEntities: ['Cinccino', 'Skitty'],
    types: ['Normal'],
    generation: 5,
  },
  {
    slug: 'cinccino',
    name: 'Cinccino',
    collection: 'tiny-and-adorable',
    extraCollections: ['mice'],
    translations: [],
    relatedKeywords: ['cinccino cards', 'fluff aesthetic pokemon cards'],
    relatedEntities: ['Minccino', 'Skitty'],
    types: ['Normal'],
    generation: 5,
  },
  {
    slug: 'skitty',
    name: 'Skitty',
    collection: 'tiny-and-adorable',
    extraCollections: ['cats'],
    translations: [],
    relatedKeywords: ['skitty cards', 'cute cat pokemon cards'],
    relatedEntities: ['Delcatty', 'Teddiursa'],
    types: ['Normal'],
    generation: 3,
  },
  {
    slug: 'delcatty',
    name: 'Delcatty',
    collection: 'tiny-and-adorable',
    extraCollections: ['cats'],
    translations: [],
    relatedKeywords: ['delcatty cards', 'cute cat pokemon card collection'],
    relatedEntities: ['Skitty', 'Sylveon'],
    types: ['Normal'],
    generation: 3,
  },
  {
    slug: 'snom',
    name: 'Snom',
    collection: 'tiny-and-adorable',
    translations: ['ユキハミ', '雪汪汪'],
    relatedKeywords: ['snom cards', 'cute ice bug pokemon cards'],
    relatedEntities: ['Frosmoth', 'Cutiefly'],
    types: ['Ice', 'Bug'],
    generation: 8,
  },
  {
    slug: 'piplup',
    name: 'Piplup',
    collection: 'tiny-and-adorable',
    extraCollections: ['all-other-animals'],
    translations: ['ポッチャマ', '波加曼'],
    relatedKeywords: ['piplup cards', 'cute penguin pokemon cards', 'piplup starter cards'],
    relatedEntities: ['Primarina', 'Marill'],
    types: ['Water'],
    generation: 4,
  },
  {
    slug: 'emolga',
    name: 'Emolga',
    collection: 'tiny-and-adorable',
    extraCollections: ['mice'],
    translations: [],
    relatedKeywords: ['emolga cards', 'cute flying squirrel pokemon cards'],
    relatedEntities: ['Dedenne', 'Pachirisu'],
    types: ['Electric', 'Flying'],
    generation: 5,
  },
  {
    slug: 'pachirisu',
    name: 'Pachirisu',
    collection: 'tiny-and-adorable',
    extraCollections: ['mice'],
    translations: [],
    relatedKeywords: ['pachirisu cards', 'squirrel electric pokemon cards'],
    relatedEntities: ['Emolga', 'Dedenne'],
    types: ['Electric'],
    generation: 4,
  },
  {
    slug: 'joltik',
    name: 'Joltik',
    collection: 'tiny-and-adorable',
    translations: [],
    relatedKeywords: ['joltik cards', 'tiny spider pokemon cards'],
    relatedEntities: ['Galvantula', 'Cutiefly'],
    types: ['Bug', 'Electric'],
    generation: 5,
  },
  {
    slug: 'galvantula',
    name: 'Galvantula',
    collection: 'tiny-and-adorable',
    translations: [],
    relatedKeywords: ['galvantula cards', 'electric spider pokemon cards'],
    relatedEntities: ['Joltik', 'Cutiefly'],
    types: ['Bug', 'Electric'],
    generation: 5,
  },
  {
    slug: 'plusle',
    name: 'Plusle',
    collection: 'tiny-and-adorable',
    extraCollections: ['mice'],
    translations: [],
    relatedKeywords: ['plusle cards', 'cute cheering pokemon cards'],
    relatedEntities: ['Minun', 'Pichu'],
    types: ['Electric'],
    generation: 3,
  },
  {
    slug: 'minun',
    name: 'Minun',
    collection: 'tiny-and-adorable',
    extraCollections: ['mice'],
    translations: [],
    relatedKeywords: ['minun cards', 'cute cheering pokemon cards'],
    relatedEntities: ['Plusle', 'Pichu'],
    types: ['Electric'],
    generation: 3,
  },
  {
    slug: 'tinkatink',
    name: 'Tinkatink',
    collection: 'tiny-and-adorable',
    translations: [],
    relatedKeywords: ['tinkatink cards', 'cute tiny fairy pokemon cards'],
    relatedEntities: ['Tinkatuff', 'Tinkaton'],
    types: ['Fairy', 'Steel'],
    generation: 9,
  },
  {
    slug: 'tinkatuff',
    name: 'Tinkatuff',
    collection: 'tiny-and-adorable',
    translations: [],
    relatedKeywords: ['tinkatuff cards', 'hammer fairy pokemon cards'],
    relatedEntities: ['Tinkatink', 'Tinkaton'],
    types: ['Fairy', 'Steel'],
    generation: 9,
  },
  {
    slug: 'tinkaton',
    name: 'Tinkaton',
    collection: 'tiny-and-adorable',
    translations: [],
    relatedKeywords: ['tinkaton cards', 'giant hammer pokemon cards'],
    relatedEntities: ['Tinkatink', 'Tinkatuff'],
    types: ['Fairy', 'Steel'],
    generation: 9,
  },
  // ─── Food & Sweet Treats ─────────────────────────────────────────────────────
  {
    slug: 'vanillite',
    name: 'Vanillite',
    collection: 'food-and-sweet-treats',
    translations: [],
    relatedKeywords: ['vanillite cards', 'ice cream pokemon cards'],
    relatedEntities: ['Vanillish', 'Vanilluxe'],
    types: ['Ice'],
    generation: 5,
  },
  {
    slug: 'vanillish',
    name: 'Vanillish',
    collection: 'food-and-sweet-treats',
    translations: [],
    relatedKeywords: ['vanillish cards', 'cute ice cream pokemon cards'],
    relatedEntities: ['Vanillite', 'Vanilluxe'],
    types: ['Ice'],
    generation: 5,
  },
  {
    slug: 'vanilluxe',
    name: 'Vanilluxe',
    collection: 'food-and-sweet-treats',
    translations: [],
    relatedKeywords: ['vanilluxe cards', 'dessert pokemon cards'],
    relatedEntities: ['Vanillite', 'Vanillish'],
    types: ['Ice'],
    generation: 5,
  },
  {
    slug: 'fidough',
    name: 'Fidough',
    collection: 'food-and-sweet-treats',
    extraCollections: ['dogs'],
    translations: [],
    relatedKeywords: ['fidough cards', 'bread dog pokemon cards'],
    relatedEntities: ['Dachsbun', 'Milcery'],
    types: ['Fairy'],
    generation: 9,
  },
  {
    slug: 'dachsbun',
    name: 'Dachsbun',
    collection: 'food-and-sweet-treats',
    extraCollections: ['dogs'],
    translations: [],
    relatedKeywords: ['dachsbun cards', 'bakery dog pokemon cards'],
    relatedEntities: ['Fidough', 'Alcremie'],
    types: ['Fairy'],
    generation: 9,
  },
  {
    slug: 'applin',
    name: 'Applin',
    collection: 'food-and-sweet-treats',
    translations: [],
    relatedKeywords: ['applin cards', 'apple pokemon cards'],
    relatedEntities: ['Appletun', 'Dipplin'],
    types: ['Grass', 'Dragon'],
    generation: 8,
  },
  {
    slug: 'appletun',
    name: 'Appletun',
    collection: 'food-and-sweet-treats',
    translations: [],
    relatedKeywords: ['appletun cards', 'apple pie pokemon cards'],
    relatedEntities: ['Applin', 'Dipplin'],
    types: ['Grass', 'Dragon'],
    generation: 8,
  },
  {
    slug: 'dipplin',
    name: 'Dipplin',
    collection: 'food-and-sweet-treats',
    translations: [],
    relatedKeywords: ['dipplin cards', 'candied apple pokemon cards'],
    relatedEntities: ['Applin', 'Appletun'],
    types: ['Grass', 'Dragon'],
    generation: 9,
  },
  {
    slug: 'sinistea',
    name: 'Sinistea',
    collection: 'food-and-sweet-treats',
    translations: [],
    relatedKeywords: ['sinistea cards', 'tea cup pokemon cards'],
    relatedEntities: ['Polteageist', 'Alcremie'],
    types: ['Ghost'],
    generation: 8,
  },
  {
    slug: 'polteageist',
    name: 'Polteageist',
    collection: 'food-and-sweet-treats',
    translations: [],
    relatedKeywords: ['polteageist cards', 'tea party pokemon cards'],
    relatedEntities: ['Sinistea', 'Swirlix'],
    types: ['Ghost'],
    generation: 8,
  },
  // ─── Cottagecore & Floral ────────────────────────────────────────────────────
  {
    slug: 'oddish',
    name: 'Oddish',
    collection: 'cottagecore-and-floral',
    translations: [],
    relatedKeywords: ['oddish cards', 'plant pokemon cards'],
    relatedEntities: ['Gloom', 'Vileplume', 'Bellossom'],
    types: ['Grass', 'Poison'],
    generation: 1,
  },
  {
    slug: 'gloom',
    name: 'Gloom',
    collection: 'cottagecore-and-floral',
    translations: [],
    relatedKeywords: ['gloom cards', 'flower pokemon cards'],
    relatedEntities: ['Oddish', 'Vileplume', 'Bellossom'],
    types: ['Grass', 'Poison'],
    generation: 1,
  },
  {
    slug: 'vileplume',
    name: 'Vileplume',
    collection: 'cottagecore-and-floral',
    translations: [],
    relatedKeywords: ['vileplume cards', 'rafflesia pokemon cards'],
    relatedEntities: ['Oddish', 'Gloom', 'Bellossom'],
    types: ['Grass', 'Poison'],
    generation: 1,
  },
  {
    slug: 'bellossom',
    name: 'Bellossom',
    collection: 'cottagecore-and-floral',
    translations: [],
    relatedKeywords: ['bellossom cards', 'floral pokemon cards'],
    relatedEntities: ['Oddish', 'Gloom', 'Vileplume'],
    types: ['Grass'],
    generation: 2,
  },
  {
    slug: 'hoppip',
    name: 'Hoppip',
    collection: 'cottagecore-and-floral',
    translations: [],
    relatedKeywords: ['hoppip cards', 'meadow pokemon cards'],
    relatedEntities: ['Skiploom', 'Jumpluff'],
    types: ['Grass', 'Flying'],
    generation: 2,
  },
  {
    slug: 'skiploom',
    name: 'Skiploom',
    collection: 'cottagecore-and-floral',
    translations: [],
    relatedKeywords: ['skiploom cards', 'flower meadow pokemon cards'],
    relatedEntities: ['Hoppip', 'Jumpluff'],
    types: ['Grass', 'Flying'],
    generation: 2,
  },
  {
    slug: 'jumpluff',
    name: 'Jumpluff',
    collection: 'cottagecore-and-floral',
    translations: [],
    relatedKeywords: ['jumpluff cards', 'cotton puff pokemon cards'],
    relatedEntities: ['Hoppip', 'Skiploom'],
    types: ['Grass', 'Flying'],
    generation: 2,
  },
  {
    slug: 'cherubi',
    name: 'Cherubi',
    collection: 'cottagecore-and-floral',
    translations: [],
    relatedKeywords: ['cherubi cards', 'cherry pokemon cards'],
    relatedEntities: ['Cherrim', 'Smoliv'],
    types: ['Grass'],
    generation: 4,
  },
  {
    slug: 'cherrim',
    name: 'Cherrim',
    collection: 'cottagecore-and-floral',
    translations: [],
    relatedKeywords: ['cherrim cards', 'sunshine flower pokemon cards'],
    relatedEntities: ['Cherubi', 'Shaymin'],
    types: ['Grass'],
    generation: 4,
  },
  {
    slug: 'petilil',
    name: 'Petilil',
    collection: 'cottagecore-and-floral',
    translations: [],
    relatedKeywords: ['petilil cards', 'lily bulb pokemon cards'],
    relatedEntities: ['Lilligant', 'Flabébé'],
    types: ['Grass'],
    generation: 5,
  },
  {
    slug: 'deerling',
    name: 'Deerling',
    collection: 'cottagecore-and-floral',
    translations: [],
    relatedKeywords: ['deerling cards', 'forest cottagecore pokemon cards'],
    relatedEntities: ['Sawsbuck', 'Shaymin'],
    types: ['Normal', 'Grass'],
    generation: 5,
  },
  {
    slug: 'sawsbuck',
    name: 'Sawsbuck',
    collection: 'cottagecore-and-floral',
    translations: [],
    relatedKeywords: ['sawsbuck cards', 'seasonal deer pokemon cards'],
    relatedEntities: ['Deerling', 'Shaymin'],
    types: ['Normal', 'Grass'],
    generation: 5,
  },
  {
    slug: 'cottonee',
    name: 'Cottonee',
    collection: 'cottagecore-and-floral',
    translations: [],
    relatedKeywords: ['cottonee cards', 'cotton plant pokemon cards'],
    relatedEntities: ['Whimsicott', 'Jumpluff'],
    types: ['Grass', 'Fairy'],
    generation: 5,
  },
  {
    slug: 'whimsicott',
    name: 'Whimsicott',
    collection: 'cottagecore-and-floral',
    translations: [],
    relatedKeywords: ['whimsicott cards', 'cottagecore fairy pokemon cards'],
    relatedEntities: ['Cottonee', 'Comfey'],
    types: ['Grass', 'Fairy'],
    generation: 5,
  },
  {
    slug: 'roselia',
    name: 'Roselia',
    collection: 'cottagecore-and-floral',
    translations: [],
    relatedKeywords: ['roselia cards', 'rose pokemon cards'],
    relatedEntities: ['Budew', 'Roserade'],
    types: ['Grass', 'Poison'],
    generation: 3,
  },
  {
    slug: 'roserade',
    name: 'Roserade',
    collection: 'cottagecore-and-floral',
    translations: [],
    relatedKeywords: ['roserade cards', 'rose bouquet pokemon cards'],
    relatedEntities: ['Budew', 'Roselia'],
    types: ['Grass', 'Poison'],
    generation: 4,
  },
  {
    slug: 'smoliv',
    name: 'Smoliv',
    collection: 'cottagecore-and-floral',
    translations: [],
    relatedKeywords: ['smoliv cards', 'olive pokemon cards'],
    relatedEntities: ['Dolliv', 'Arboliva'],
    types: ['Grass', 'Normal'],
    generation: 9,
  },
  {
    slug: 'dolliv',
    name: 'Dolliv',
    collection: 'cottagecore-and-floral',
    translations: [],
    relatedKeywords: ['dolliv cards', 'olive branch pokemon cards'],
    relatedEntities: ['Smoliv', 'Arboliva'],
    types: ['Grass', 'Normal'],
    generation: 9,
  },
  {
    slug: 'arboliva',
    name: 'Arboliva',
    collection: 'cottagecore-and-floral',
    translations: [],
    relatedKeywords: ['arboliva cards', 'olive tree pokemon cards'],
    relatedEntities: ['Smoliv', 'Dolliv'],
    types: ['Grass', 'Normal'],
    generation: 9,
  },
  {
    slug: 'gossifleur',
    name: 'Gossifleur',
    collection: 'cottagecore-and-floral',
    translations: [],
    relatedKeywords: ['gossifleur cards', 'flower garden pokemon cards'],
    relatedEntities: ['Eldegoss', 'Flabébé'],
    types: ['Grass'],
    generation: 8,
  },
  {
    slug: 'eldegoss',
    name: 'Eldegoss',
    collection: 'cottagecore-and-floral',
    translations: [],
    relatedKeywords: ['eldegoss cards', 'cottonee style pokemon cards'],
    relatedEntities: ['Gossifleur', 'Whimsicott'],
    types: ['Grass'],
    generation: 8,
  },
  // ─── Animal Collections ───────────────────────────────────────────────────────
  {
    slug: 'growlithe',
    name: 'Growlithe',
    collection: 'dogs',
    translations: ['ガーディ', '卡蒂狗'],
    relatedKeywords: ['growlithe cards', 'cute puppy pokemon cards'],
    relatedEntities: ['Arcanine', 'Yamper', 'Fidough'],
    types: ['Fire'],
    generation: 1,
  },
  {
    slug: 'arcanine',
    name: 'Arcanine',
    collection: 'dogs',
    translations: ['ウインディ', '风速狗'],
    relatedKeywords: ['arcanine cards', 'legendary dog pokemon cards'],
    relatedEntities: ['Growlithe', 'Yamper', 'Boltund'],
    types: ['Fire'],
    generation: 1,
  },
  {
    slug: 'yamper',
    name: 'Yamper',
    collection: 'dogs',
    translations: [],
    relatedKeywords: ['yamper cards', 'cute corgi pokemon cards'],
    relatedEntities: ['Boltund', 'Fidough'],
    types: ['Electric'],
    generation: 8,
  },
  {
    slug: 'boltund',
    name: 'Boltund',
    collection: 'dogs',
    translations: [],
    relatedKeywords: ['boltund cards', 'electric dog pokemon cards'],
    relatedEntities: ['Yamper', 'Arcanine', 'Growlithe'],
    types: ['Electric'],
    generation: 8,
  },
  {
    slug: 'rockruff',
    name: 'Rockruff',
    collection: 'dogs',
    translations: [],
    relatedKeywords: ['rockruff cards', 'puppy wolf pokemon cards'],
    relatedEntities: ['Lycanroc', 'Growlithe'],
    types: ['Rock'],
    generation: 7,
  },
  {
    slug: 'lycanroc',
    name: 'Lycanroc',
    collection: 'dogs',
    translations: [],
    relatedKeywords: ['lycanroc cards', 'wolf pokemon cards'],
    relatedEntities: ['Rockruff', 'Arcanine'],
    types: ['Rock'],
    generation: 7,
  },
  {
    slug: 'houndour',
    name: 'Houndour',
    collection: 'dogs',
    translations: [],
    relatedKeywords: ['houndour cards', 'dark dog pokemon cards'],
    relatedEntities: ['Houndoom', 'Growlithe'],
    types: ['Dark', 'Fire'],
    generation: 2,
  },
  {
    slug: 'houndoom',
    name: 'Houndoom',
    collection: 'dogs',
    translations: [],
    relatedKeywords: ['houndoom cards', 'hellhound pokemon cards'],
    relatedEntities: ['Houndour', 'Arcanine'],
    types: ['Dark', 'Fire'],
    generation: 2,
  },
  {
    slug: 'sprigatito',
    name: 'Sprigatito',
    collection: 'cats',
    translations: [],
    relatedKeywords: ['sprigatito cards', 'grass cat pokemon cards'],
    relatedEntities: ['Floragato', 'Skitty'],
    types: ['Grass'],
    generation: 9,
  },
  {
    slug: 'floragato',
    name: 'Floragato',
    collection: 'cats',
    translations: [],
    relatedKeywords: ['floragato cards', 'yo-yo cat pokemon cards'],
    relatedEntities: ['Sprigatito', 'Skitty'],
    types: ['Grass'],
    generation: 9,
  },
  {
    slug: 'meowth',
    name: 'Meowth',
    collection: 'cats',
    translations: ['ニャース', '喵喵'],
    relatedKeywords: ['meowth cards', 'classic cat pokemon cards'],
    relatedEntities: ['Persian', 'Skitty'],
    types: ['Normal'],
    generation: 1,
  },
  {
    slug: 'persian',
    name: 'Persian',
    collection: 'cats',
    translations: [],
    relatedKeywords: ['persian cards', 'feline pokemon cards'],
    relatedEntities: ['Meowth', 'Glameow'],
    types: ['Normal'],
    generation: 1,
  },
  {
    slug: 'glameow',
    name: 'Glameow',
    collection: 'cats',
    translations: [],
    relatedKeywords: ['glameow cards', 'cute cat pokemon cards'],
    relatedEntities: ['Purugly', 'Skitty'],
    types: ['Normal'],
    generation: 4,
  },
  {
    slug: 'purugly',
    name: 'Purugly',
    collection: 'cats',
    translations: [],
    relatedKeywords: ['purugly cards', 'cat evolution pokemon cards'],
    relatedEntities: ['Glameow', 'Persian'],
    types: ['Normal'],
    generation: 4,
  },
  {
    slug: 'litten',
    name: 'Litten',
    collection: 'cats',
    translations: [],
    relatedKeywords: ['litten cards', 'fire cat starter cards'],
    relatedEntities: ['Torracat', 'Sprigatito'],
    types: ['Fire'],
    generation: 7,
  },
  {
    slug: 'torracat',
    name: 'Torracat',
    collection: 'cats',
    translations: [],
    relatedKeywords: ['torracat cards', 'fire feline pokemon cards'],
    relatedEntities: ['Litten', 'Incineroar'],
    types: ['Fire'],
    generation: 7,
  },
  {
    slug: 'incineroar',
    name: 'Incineroar',
    collection: 'cats',
    translations: [],
    relatedKeywords: ['incineroar cards', 'wrestling tiger pokemon cards'],
    relatedEntities: ['Litten', 'Torracat'],
    types: ['Fire', 'Dark'],
    generation: 7,
  },
  {
    slug: 'scorbunny',
    name: 'Scorbunny',
    collection: 'bunny',
    translations: [],
    relatedKeywords: ['scorbunny cards', 'rabbit starter pokemon cards'],
    relatedEntities: ['Raboot', 'Cinderace', 'Buneary'],
    types: ['Fire'],
    generation: 8,
  },
  {
    slug: 'raboot',
    name: 'Raboot',
    collection: 'bunny',
    translations: [],
    relatedKeywords: ['raboot cards', 'rabbit pokemon evolution cards'],
    relatedEntities: ['Scorbunny', 'Cinderace', 'Bunnelby'],
    types: ['Fire'],
    generation: 8,
  },
  {
    slug: 'cinderace',
    name: 'Cinderace',
    collection: 'bunny',
    translations: [],
    relatedKeywords: ['cinderace cards', 'rabbit striker pokemon cards'],
    relatedEntities: ['Scorbunny', 'Raboot'],
    types: ['Fire'],
    generation: 8,
  },
  {
    slug: 'bunnelby',
    name: 'Bunnelby',
    collection: 'bunny',
    translations: [],
    relatedKeywords: ['bunnelby cards', 'digging rabbit pokemon cards'],
    relatedEntities: ['Diggersby', 'Buneary'],
    types: ['Normal'],
    generation: 6,
  },
  {
    slug: 'diggersby',
    name: 'Diggersby',
    collection: 'bunny',
    translations: [],
    relatedKeywords: ['diggersby cards', 'rabbit ground pokemon cards'],
    relatedEntities: ['Bunnelby', 'Lopunny'],
    types: ['Normal', 'Ground'],
    generation: 6,
  },
  {
    slug: 'pikachu',
    name: 'Pikachu',
    collection: 'mice',
    translations: ['ピカチュウ', '皮卡丘'],
    relatedKeywords: ['pikachu cards', 'mouse pokemon cards'],
    relatedEntities: ['Pichu', 'Raichu', 'Pawmi', 'Dedenne'],
    types: ['Electric'],
    generation: 1,
  },
  {
    slug: 'raichu',
    name: 'Raichu',
    collection: 'mice',
    translations: ['ライチュウ', '雷丘'],
    relatedKeywords: ['raichu cards', 'electric mouse pokemon cards'],
    relatedEntities: ['Pichu', 'Pikachu', 'Pawmi'],
    types: ['Electric'],
    generation: 1,
  },
  {
    slug: 'spheal',
    name: 'Spheal',
    collection: 'all-other-animals',
    translations: [],
    relatedKeywords: ['spheal cards', 'seal pokemon cards'],
    relatedEntities: ['Sealeo', 'Walrein', 'Piplup'],
    types: ['Ice', 'Water'],
    generation: 3,
  },
  {
    slug: 'sealeo',
    name: 'Sealeo',
    collection: 'all-other-animals',
    translations: [],
    relatedKeywords: ['sealeo cards', 'rolling seal pokemon cards'],
    relatedEntities: ['Spheal', 'Walrein'],
    types: ['Ice', 'Water'],
    generation: 3,
  },
  {
    slug: 'walrein',
    name: 'Walrein',
    collection: 'all-other-animals',
    translations: [],
    relatedKeywords: ['walrein cards', 'walrus pokemon cards'],
    relatedEntities: ['Spheal', 'Sealeo'],
    types: ['Ice', 'Water'],
    generation: 3,
  },
  {
    slug: 'girafarig',
    name: 'Girafarig',
    collection: 'all-other-animals',
    translations: [],
    relatedKeywords: ['girafarig cards', 'giraffe pokemon cards'],
    relatedEntities: ['Farigiraf', 'Deerling'],
    types: ['Normal', 'Psychic'],
    generation: 2,
  },
  {
    slug: 'farigiraf',
    name: 'Farigiraf',
    collection: 'all-other-animals',
    translations: [],
    relatedKeywords: ['farigiraf cards', 'long neck pokemon cards'],
    relatedEntities: ['Girafarig', 'Deerling'],
    types: ['Normal', 'Psychic'],
    generation: 9,
  },
  {
    slug: 'miltank',
    name: 'Miltank',
    collection: 'all-other-animals',
    translations: [],
    relatedKeywords: ['miltank cards', 'cow pokemon cards'],
    relatedEntities: ['Tauros', 'Wooloo'],
    types: ['Normal'],
    generation: 2,
  },
  {
    slug: 'tauros',
    name: 'Tauros',
    collection: 'all-other-animals',
    translations: [],
    relatedKeywords: ['tauros cards', 'wild bull pokemon cards'],
    relatedEntities: ['Miltank', 'Wooloo'],
    types: ['Normal'],
    generation: 1,
  },
  {
    slug: 'cubchoo',
    name: 'Cubchoo',
    collection: 'all-other-animals',
    translations: [],
    relatedKeywords: ['cubchoo cards', 'bear cub pokemon cards'],
    relatedEntities: ['Beartic', 'Teddiursa'],
    types: ['Ice'],
    generation: 5,
  },
  {
    slug: 'beartic',
    name: 'Beartic',
    collection: 'all-other-animals',
    translations: [],
    relatedKeywords: ['beartic cards', 'polar bear pokemon cards'],
    relatedEntities: ['Cubchoo', 'Walrein'],
    types: ['Ice'],
    generation: 5,
  },
  {
    slug: 'stufful',
    name: 'Stufful',
    collection: 'all-other-animals',
    translations: [],
    relatedKeywords: ['stufful cards', 'plush bear pokemon cards'],
    relatedEntities: ['Bewear', 'Teddiursa'],
    types: ['Normal', 'Fighting'],
    generation: 7,
  },
  {
    slug: 'bewear',
    name: 'Bewear',
    collection: 'all-other-animals',
    translations: [],
    relatedKeywords: ['bewear cards', 'bear hug pokemon cards'],
    relatedEntities: ['Stufful', 'Teddiursa'],
    types: ['Normal', 'Fighting'],
    generation: 7,
  },
  {
    slug: 'wooloo',
    name: 'Wooloo',
    collection: 'all-other-animals',
    translations: [],
    relatedKeywords: ['wooloo cards', 'sheep pokemon cards'],
    relatedEntities: ['Dubwool', 'Miltank'],
    types: ['Normal'],
    generation: 8,
  },
  {
    slug: 'dubwool',
    name: 'Dubwool',
    collection: 'all-other-animals',
    translations: [],
    relatedKeywords: ['dubwool cards', 'sheep evolution pokemon cards'],
    relatedEntities: ['Wooloo', 'Miltank'],
    types: ['Normal'],
    generation: 8,
  },
  // ─── Dreamy & Ethereal ───────────────────────────────────────────────────────
  {
    slug: 'jirachi',
    name: 'Jirachi',
    collection: 'dreamy-and-ethereal',
    translations: ['ジラーチ', '基拉祈'],
    relatedKeywords: ['jirachi star cards', 'cute jirachi cards'],
    relatedEntities: ['Mew', 'Cresselia', 'Victini'],
    types: ['Steel', 'Psychic'],
    generation: 3,
  },
  {
    slug: 'munna',
    name: 'Munna',
    collection: 'dreamy-and-ethereal',
    translations: [],
    relatedKeywords: ['munna cards', 'dreamy cloud pokemon cards'],
    relatedEntities: ['Musharna', 'Cresselia'],
    types: ['Psychic'],
    generation: 5,
  },
  {
    slug: 'musharna',
    name: 'Musharna',
    collection: 'dreamy-and-ethereal',
    translations: [],
    relatedKeywords: ['musharna cards', 'dream aesthetic pokemon cards'],
    relatedEntities: ['Munna', 'Cresselia'],
    types: ['Psychic'],
    generation: 5,
  },
  {
    slug: 'victini',
    name: 'Victini',
    collection: 'dreamy-and-ethereal',
    translations: ['ビクティニ', '比克提尼'],
    relatedKeywords: ['victini cards', 'victini victory pokemon cards', 'victini mythical cards'],
    relatedEntities: ['Jirachi', 'Mew'],
    types: ['Psychic', 'Fire'],
    generation: 5,
  },
  {
    slug: 'shaymin',
    name: 'Shaymin',
    collection: 'cottagecore-and-floral',
    translations: ['シェイミ', '谢米'],
    relatedKeywords: ['shaymin land forme cards', 'cottagecore pokemon cards'],
    relatedEntities: ['Leafeon', 'Jirachi'],
    types: ['Grass'],
    generation: 4,
  },
  {
    slug: 'comfey',
    name: 'Comfey',
    collection: 'cottagecore-and-floral',
    translations: [],
    relatedKeywords: ['comfey cards', 'flower pokemon card collection'],
    relatedEntities: ['Leafeon', 'Lilligant'],
    types: ['Fairy'],
    generation: 7,
  },
  {
    slug: 'cosmog',
    name: 'Cosmog',
    collection: 'dreamy-and-ethereal',
    translations: [],
    relatedKeywords: ['cosmog collection', 'starry pokemon cards'],
    relatedEntities: ['Jirachi', 'Cresselia'],
    types: ['Psychic'],
    generation: 7,
  },
  // ─── Elegant & Feminine ──────────────────────────────────────────────────────
  {
    slug: 'togekiss',
    name: 'Togekiss',
    collection: 'elegant-and-feminine',
    translations: ['トゲキッス', '波克基斯'],
    relatedKeywords: ['togekiss cards', 'elegant fairy pokemon cards'],
    relatedEntities: ['Togepi', 'Togetic'],
    types: ['Normal', 'Fairy'],
    generation: 4,
  },
  {
    slug: 'lopunny',
    name: 'Lopunny',
    collection: 'elegant-and-feminine',
    extraCollections: ['bunny'],
    translations: ['ミミロップ', '长耳兔'],
    relatedKeywords: ['lopunny cards', 'elegant bunny pokemon cards'],
    relatedEntities: ['Buneary', 'Sylveon'],
    types: ['Normal'],
    generation: 4,
  },
  {
    slug: 'primarina',
    name: 'Primarina',
    collection: 'elegant-and-feminine',
    translations: ['アシレーヌ', '西瓦顿'],
    relatedKeywords: ['primarina cards', 'elegant mermaid pokemon cards'],
    relatedEntities: ['Milotic', 'Sylveon'],
    types: ['Water', 'Fairy'],
    generation: 7,
  },
  {
    slug: 'gardevoir',
    name: 'Gardevoir',
    collection: 'elegant-and-feminine',
    translations: ['サーナイト', '沙奈朵'],
    relatedKeywords: ['gardevoir art rare cards', 'gardevoir sir cards'],
    relatedEntities: ['Kirlia', 'Diancie'],
    types: ['Psychic', 'Fairy'],
    generation: 3,
  },
  {
    slug: 'kirlia',
    name: 'Kirlia',
    collection: 'elegant-and-feminine',
    translations: [],
    relatedKeywords: ['kirlia cards', 'kirlia art rare pokemon'],
    relatedEntities: ['Gardevoir', 'Diancie'],
    types: ['Psychic', 'Fairy'],
    generation: 3,
  },
  {
    slug: 'lilligant',
    name: 'Lilligant',
    collection: 'cottagecore-and-floral',
    translations: [],
    relatedKeywords: ['lilligant cards', 'hisuian lilligant cards'],
    relatedEntities: ['Leafeon', 'Tsareena'],
    types: ['Grass'],
    generation: 5,
  },
  {
    slug: 'tsareena',
    name: 'Tsareena',
    collection: 'elegant-and-feminine',
    translations: [],
    relatedKeywords: ['tsareena cards', 'elegant pokemon cards'],
    relatedEntities: ['Lilligant', 'Milotic'],
    types: ['Grass'],
    generation: 7,
  },
  {
    slug: 'milotic',
    name: 'Milotic',
    collection: 'elegant-and-feminine',
    translations: ['ミロカロス', '美纳斯'],
    relatedKeywords: ['milotic beautiful pokemon card', 'milotic art rare'],
    relatedEntities: ['Cresselia', 'Altaria'],
    types: ['Water'],
    generation: 3,
  },
  {
    slug: 'altaria',
    name: 'Altaria',
    collection: 'elegant-and-feminine',
    translations: [],
    relatedKeywords: ['altaria cards', 'cloud bird pokemon cards'],
    relatedEntities: ['Milotic', 'Cresselia'],
    types: ['Dragon', 'Flying'],
    generation: 3,
  },
  {
    slug: 'cresselia',
    name: 'Cresselia',
    collection: 'elegant-and-feminine',
    translations: ['クレセリア', '克雷色利亚'],
    relatedKeywords: ['cresselia cards', 'dreamy cresselia pokemon cards'],
    relatedEntities: ['Mew', 'Jirachi'],
    types: ['Psychic'],
    generation: 4,
  },
  {
    slug: 'diancie',
    name: 'Diancie',
    collection: 'elegant-and-feminine',
    translations: [],
    relatedKeywords: ['diancie cards', 'princess jewel pokemon cards'],
    relatedEntities: ['Gardevoir', 'Kirlia'],
    types: ['Rock', 'Fairy'],
    generation: 6,
  },
  {
    slug: 'meloetta',
    name: 'Meloetta',
    collection: 'elegant-and-feminine',
    translations: [],
    relatedKeywords: ['meloetta cards', 'elegant psychic pokemon cards'],
    relatedEntities: ['Diancie', 'Cresselia'],
    types: ['Normal', 'Psychic'],
    generation: 5,
  },
  // ─── Spooky-Cute ─────────────────────────────────────────────────────────────
  {
    slug: 'mimikyu',
    name: 'Mimikyu',
    collection: 'spooky-cute',
    translations: ['ミミッキュ', '谜拟丘'],
    relatedKeywords: ['mimikyu illustration rare', 'mimikyu art rare cards'],
    relatedEntities: ['Espurr', 'Misdreavus'],
    types: ['Ghost', 'Fairy'],
    generation: 7,
  },
  {
    slug: 'espurr',
    name: 'Espurr',
    collection: 'spooky-cute',
    translations: ['ニャスパー', '妙喵'],
    relatedKeywords: ['espurr card collection', 'cute espurr cards'],
    relatedEntities: ['Meowstic', 'Mimikyu'],
    types: ['Psychic'],
    generation: 6,
  },
  {
    slug: 'meowstic',
    name: 'Meowstic',
    collection: 'spooky-cute',
    extraCollections: ['cats'],
    translations: [],
    relatedKeywords: ['meowstic cards', 'cute spooky psychic pokemon cards'],
    relatedEntities: ['Espurr', 'Mimikyu'],
    types: ['Psychic'],
    generation: 6,
  },
  {
    slug: 'misdreavus',
    name: 'Misdreavus',
    collection: 'spooky-cute',
    translations: [],
    relatedKeywords: ['misdreavus cards', 'spooky cute ghost pokemon cards'],
    relatedEntities: ['Mimikyu', 'Pumpkaboo'],
    types: ['Ghost'],
    generation: 2,
  },
  {
    slug: 'greavard',
    name: 'Greavard',
    collection: 'spooky-cute',
    extraCollections: ['dogs'],
    translations: [],
    relatedKeywords: ['greavard ghost dog pokemon card', 'greavard cards'],
    relatedEntities: ['Mimikyu', 'Pumpkaboo'],
    types: ['Ghost'],
    generation: 9,
  },
  {
    slug: 'pumpkaboo',
    name: 'Pumpkaboo',
    collection: 'spooky-cute',
    translations: [],
    relatedKeywords: ['pumpkaboo halloween pokemon cards', 'pumpkaboo fall pokemon cards'],
    relatedEntities: ['Misdreavus', 'Greavard'],
    types: ['Ghost', 'Grass'],
    generation: 6,
  },
  {
    slug: 'litwick',
    name: 'Litwick',
    collection: 'spooky-cute',
    translations: ['ヒトモシ', '蜡火'],
    relatedKeywords: ['litwick cards', 'cute candle ghost pokemon cards'],
    relatedEntities: ['Mimikyu', 'Misdreavus'],
    types: ['Ghost', 'Fire'],
    generation: 5,
  },
  {
    slug: 'froslass',
    name: 'Froslass',
    collection: 'spooky-cute',
    translations: ['ユキメノコ', '雪妖女'],
    relatedKeywords: ['froslass cards', 'ice ghost pokemon cards'],
    relatedEntities: ['Mimikyu', 'Misdreavus'],
    types: ['Ice', 'Ghost'],
    generation: 4,
  },
  {
    slug: 'frosmoth',
    name: 'Frosmoth',
    collection: 'spooky-cute',
    translations: ['モスノウ', '雪蛾女'],
    relatedKeywords: ['frosmoth cards', 'elegant ice moth pokemon cards'],
    relatedEntities: ['Snom', 'Froslass'],
    types: ['Ice', 'Bug'],
    generation: 8,
  },
  {
    slug: 'gengar',
    name: 'Gengar',
    collection: 'spooky-cute',
    translations: ['ゲンガー', '耿鬼'],
    relatedKeywords: ['gengar cards', 'gengar illustration rare', 'cute ghost pokemon cards'],
    relatedEntities: ['Mimikyu', 'Misdreavus'],
    types: ['Ghost', 'Poison'],
    generation: 1,
  },
]

export const SPECIES_KEYWORD_CONFIGS = Object.fromEntries(
  SPECIES_KEYWORD_SEEDS.map((species) => [species.slug, species])
) as Record<string, SpeciesKeywordConfig>

const GENERATION_ROMAN = ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII', 'IX'] as const

/** Returns a human-readable generation label like "Generation VI". */
export function generationLabel(gen: number): string {
  const roman = GENERATION_ROMAN[gen - 1] ?? String(gen)
  return `Generation ${roman}`
}

/** Shared SEO defaults for the landing page and sitewide marketing metadata. */
export const LANDING_SEO = {
  description:
    'Pink Binder is a cute Pokémon card shop and content brand for pink Pokémon card collections, kawaii binder finds, pastel fairy cards, baby shinies, and illustration rares in English, Japanese, and Chinese.',
  keywords: uniqueKeywords([
    ...SEO_KEYWORD_GROUPS.collectors,
    ...SEO_KEYWORD_GROUPS.cuteBrand,
    ...SEO_KEYWORD_GROUPS.pinkPalace,
    ...SEO_KEYWORD_GROUPS.cottagecoreAndFloral,
    ...SEO_KEYWORD_GROUPS.spaceAndDreams,
    ...SEO_KEYWORD_GROUPS.cozyAndSoft,
    ...SEO_KEYWORD_GROUPS.babies,
    ...SEO_KEYWORD_GROUPS.tinyAndAdorable,
    ...SEO_KEYWORD_GROUPS.foodAndSweetTreats,
    ...SEO_KEYWORD_GROUPS.dogs,
    ...SEO_KEYWORD_GROUPS.cats,
    ...SEO_KEYWORD_GROUPS.bunnies,
    ...SEO_KEYWORD_GROUPS.mice,
    ...SEO_KEYWORD_GROUPS.allOtherAnimals,
    ...SEO_KEYWORD_GROUPS.elegantAndFeminine,
    ...SEO_KEYWORD_GROUPS.spookyCute,
    ...SEO_KEYWORD_GROUPS.eeveelutions,
    ...SEO_KEYWORD_GROUPS.rarity,
    ...SEO_KEYWORD_GROUPS.languages,
    'pink binder pokemon',
    'girly pokemon cards',
    'pokemon card streamer',
  ]),
}

/** Shared SEO defaults for blog layouts and post discovery surfaces. */
export const BLOG_SEO = {
  description:
    'Pokémon card stories, collecting tips, and product updates from Pink Binder, with a focus on cute Pokémon cards, aesthetic binders, pastel fairy lines, baby shinies, reverse holos, and art or illustration rares.',
  keywords: uniqueKeywords([
    ...SEO_KEYWORD_GROUPS.blog,
    ...SEO_KEYWORD_GROUPS.cuteBrand,
    ...SEO_KEYWORD_GROUPS.pinkPalace,
    ...SEO_KEYWORD_GROUPS.cottagecoreAndFloral,
    ...SEO_KEYWORD_GROUPS.spaceAndDreams,
    ...SEO_KEYWORD_GROUPS.cozyAndSoft,
    ...SEO_KEYWORD_GROUPS.babies,
    ...SEO_KEYWORD_GROUPS.tinyAndAdorable,
    ...SEO_KEYWORD_GROUPS.foodAndSweetTreats,
    ...SEO_KEYWORD_GROUPS.dogs,
    ...SEO_KEYWORD_GROUPS.cats,
    ...SEO_KEYWORD_GROUPS.bunnies,
    ...SEO_KEYWORD_GROUPS.mice,
    ...SEO_KEYWORD_GROUPS.allOtherAnimals,
    ...SEO_KEYWORD_GROUPS.elegantAndFeminine,
    ...SEO_KEYWORD_GROUPS.spookyCute,
    ...SEO_KEYWORD_GROUPS.eeveelutions,
    ...SEO_KEYWORD_GROUPS.rarity,
    ...SEO_KEYWORD_GROUPS.languages,
    ...SEO_KEYWORD_GROUPS.speciesMoats,
    'pink binder blog',
    'pokemon card shop news',
  ]),
}

export const BLOG_INDEX_SEO = {
  title: 'Pokémon Card Blog: Cute Card Picks, Tips, and Updates',
  description:
    'Explore Pink Binder posts about cute Pokémon cards, pink Pokémon card collections, kawaii binder picks, fairy lines, baby shinies, reverse holos, and illustration rares in English, Japanese, and Chinese sets.',
  keywords: uniqueKeywords([
    ...BLOG_SEO.keywords,
    'pokemon card blog',
    'cute pokemon cards',
    'aesthetic pokemon card binder',
  ]),
}

export function getSpeciesKeywordConfig(species: string) {
  const lookupKey = normalizeLookupValue(species)

  return SPECIES_KEYWORD_SEEDS.find((entry) =>
    [entry.slug, entry.name, ...entry.translations, ...(entry.relatedEntities ?? [])]
      .map(normalizeLookupValue)
      .includes(lookupKey)
  )
}

/**
 * Precise species lookup that matches only by slug, name, and translations.
 * Unlike {@link getSpeciesKeywordConfig}, this does NOT search `relatedEntities`,
 * which prevents false positives where one species' relatedEntities list causes
 * a different species to be returned.
 */
export function getSpeciesConfigBySlugOrName(species: string): SpeciesKeywordConfig | undefined {
  const lookupKey = normalizeLookupValue(species)

  return SPECIES_KEYWORD_SEEDS.find((entry) =>
    [entry.slug, entry.name, ...entry.translations].map(normalizeLookupValue).includes(lookupKey)
  )
}

export function createSpeciesPageSeoConfig(
  species: string | SpeciesKeywordConfig,
  options: SpeciesSeoConfigInput = {}
) {
  const resolved =
    typeof species === 'string'
      ? (getSpeciesKeywordConfig(species) ?? {
          slug: slugifySpecies(species),
          name: species,
          collection: 'dreamy-and-ethereal' as const,
          translations: [],
          relatedKeywords: [],
        })
      : species

  const siteName = options.siteName ?? BRAND.name
  const collection = SPECIES_COLLECTIONS[resolved.collection]
  const collectionSlugs = [...new Set([resolved.collection, ...(resolved.extraCollections ?? [])])]
  const collectionTitles = collectionSlugs.map((slug) => SPECIES_COLLECTIONS[slug].title)
  const titleLead = resolved.titleName ?? resolved.name
  const collectionKeywords = collectionSlugs.flatMap(
    (slug) => SPECIES_COLLECTION_KEYWORDS[slug] ?? []
  )

  return {
    slug: resolved.slug,
    name: resolved.name,
    collection,
    collections: collectionSlugs.map((slug) => SPECIES_COLLECTIONS[slug]),
    translations: resolved.translations,
    title: `${titleLead} Cute Cards | ${siteName}`,
    description: `Shop the cutest ${resolved.name} cards in English, Japanese, and Chinese. From rare Illustration Rares to shiny baby cards, we specialize in the pink and pastel side of Pokémon TCG. Fast shipping on all Fairy and Art Rare cards.`,
    heading: `The Ultimate ${resolved.name} Collection: Cute & Rare Cards`,
    keywords: uniqueKeywords([
      resolved.name,
      titleLead,
      ...resolved.translations,
      ...collectionTitles,
      ...resolved.relatedKeywords,
      ...(resolved.relatedEntities ?? []),
      ...(options.includeKeywordGroups === false ? [] : collectionKeywords),
      ...(options.includeKeywordGroups === false ? [] : SEO_KEYWORD_GROUPS.rarity),
      ...SEO_KEYWORD_GROUPS.languages,
      ...(options.customKeywords ?? []),
    ]),
  }
}

export function createPostKeywordConfig(input: PostKeywordConfigInput) {
  const matchedSpecies = uniqueSpecies([...(input.species ?? []), ...(input.tags ?? [])])

  return {
    matchedSpecies,
    keywords: uniqueKeywords([
      input.title,
      ...BLOG_SEO.keywords,
      ...(input.tags ?? []),
      ...(input.keywords ?? []),
      ...matchedSpecies.flatMap(
        (species) => createSpeciesPageSeoConfig(species, { includeKeywordGroups: false }).keywords
      ),
    ]),
  }
}

function uniqueKeywords(keywords: Iterable<string>) {
  const seen = new Set<string>()
  const result: string[] = []

  for (const keyword of keywords) {
    const trimmed = keyword.trim()

    if (!trimmed) {
      continue
    }

    const key = trimmed.toLowerCase()

    if (seen.has(key)) {
      continue
    }

    seen.add(key)
    result.push(trimmed)
  }

  return result
}

function uniqueSpecies(species: string[]) {
  const seen = new Set<string>()
  const result: SpeciesKeywordConfig[] = []

  for (const entry of species) {
    const resolved = getSpeciesKeywordConfig(entry)

    if (!resolved || seen.has(resolved.slug)) {
      continue
    }

    seen.add(resolved.slug)
    result.push(resolved)
  }

  return result
}

function normalizeLookupValue(value: string) {
  return value
    .trim()
    .toLowerCase()
    .replace(/[-_/]+/g, ' ')
}

function slugifySpecies(value: string) {
  return (
    value
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '') || 'pokemon'
  )
}
