export const LANDING_SEO = {
  description:
    'Pink Binder is a cute Pokémon card shop and content brand for pink Pokémon card collections, kawaii binder finds, pastel fairy cards, baby shinies, and illustration rares in English, Japanese, and Chinese.',
  keywords: [
    'pokemon card shop',
    'pokemon card collector',
    'pokemon tcg puerto rico',
    'pokemon card live shopping',
    'cute pokemon cards for sale',
    'pink pokemon card collection',
    'kawaii pokemon cards',
    'aesthetic pokemon card binder',
    'pastel fairy type cards',
    'adorable baby shiny pokemon',
    'cute pokemon cards',
    'girly pokemon cards',
    'cute pokemon tcg shop',
    'pink pokemon cards',
    'sylveon collection',
    'pastel tcg',
    'fairy pokemon card binder',
    'floral pokemon cards',
    'cottagecore pokemon cards',
    'plant pokemon cards',
    'comfey cards',
    'shaymin land forme cards',
    'jirachi cards',
    'starry pokemon cards',
    'cosmog collection',
    'dreamy pokemon cards',
    'fluffy pokemon',
    'teddiursa cards',
    'cozy card binder',
    'soft aesthetic pokemon cards',
    'baby pokemon cards',
    'actual baby pokemon cards',
    'baby shiny pokemon',
    'starter pokemon cards',
    'pokemon starter base forms',
    'cute starter pokemon cards',
    'tiny cute pokemon cards',
    'small adorable pokemon cards',
    'tiny pokemon card collection',
    'dessert pokemon cards',
    'food pokemon cards',
    'sweet treats pokemon cards',
    'cute bakery pokemon cards',
    'dog pokemon cards',
    'puppy pokemon cards',
    'cute dog pokemon collection',
    'cat pokemon cards',
    'kitten pokemon cards',
    'cute cat pokemon collection',
    'bunny pokemon cards',
    'rabbit pokemon cards',
    'cute bunny pokemon collection',
    'mouse pokemon cards',
    'cute mice pokemon cards',
    'pikachu clone pokemon cards',
    'bird pokemon cards',
    'owl pokemon cards',
    'penguin pokemon cards',
    'duck pokemon cards',
    'fish pokemon cards',
    'koi pokemon cards',
    'aquatic pokemon cards',
    'sea life pokemon cards',
    'seal pokemon cards',
    'fox pokemon cards',
    'deer pokemon cards',
    'giraffe pokemon cards',
    'cow pokemon cards',
    'bear pokemon cards',
    'animal pokemon collection',
    'elegant pokemon cards',
    'feminine pokemon card collection',
    'pokemon special illustration rare',
    'spooky cute pokemon cards',
    'ghost pokemon cute collection',
    'mimikyu fan cards',
    'eeveelution cards',
    'eevee evolution cards',
    'sylveon espeon glaceon leafeon cards',
    'most popular pokemon cards',
    'top pokemon fan favorites',
    'iconic pokemon cards all generations',
    'legendary pokemon cards',
    'legendary pokemon collection',
    'pokemon legendary card binder',
    'mythical pokemon cards',
    'mythical pokemon collection',
    'pokemon mythical card binder',
    'Scarlet & Violet Illustration Rare cards',
    'Art Rare pokemon collection',
    'Japanese waifu cards',
    'CHV (Chinese) pokemon cards',
    'Special Illustration Rare (SIR) price guide',
    'english pokemon cards',
    'japanese pokemon cards',
    'chinese pokemon cards',
    'bug pokemon cards',
    'insect pokemon cards',
    'butterfly pokemon cards',
    'beetle pokemon card collection',
    'cute bear pokemon collection',
    'ursaring pokemon cards',
    'dragon pokemon cards',
    'dragon type pokemon collection',
    'dragonite cards',
    'cute dragon pokemon tcg',
    'sea creature pokemon cards',
    'ocean pokemon cards',
    'jellyfish pokemon cards',
    'seahorse pokemon collection',
    'ice pokemon cards',
    'ice type pokemon collection',
    'winter pokemon cards',
    'snow pokemon card binder',
    'electric pokemon cards',
    'pikachu clone cards',
    'electric cute pokemon',
    'pikachu-like pokemon collection',
    'fairy type pokemon cards',
    'fairy pokemon collection',
    'magical pokemon cards',
    'enchanting fairy pokemon tcg',
    'round pokemon cards',
    'squishy pokemon cards',
    'blob pokemon collection',
    'cute round pokemon tcg',
    'dark type pokemon cards',
    'dark pokemon collection',
    'umbreon dark cards',
    'edgy pokemon card binder',
    'fighting pokemon cards',
    'fighting type collection',
    'lucario cards',
    'martial arts pokemon tcg',
    'fossil pokemon cards',
    'dinosaur pokemon cards',
    'prehistoric pokemon collection',
    'fossil pokemon card binder',
    'beach pokemon cards',
    'ocean pokemon collection',
    'coastal pokemon cards',
    'beach vibes pokemon tcg',
    'valentine pokemon cards',
    'love pokemon cards',
    'heart pokemon collection',
    'romantic pokemon card binder',
    'halloween pokemon cards',
    'spooky pokemon collection',
    'ghost pokemon cards halloween',
    'creepy cute pokemon tcg',
    'christmas pokemon cards',
    'holiday pokemon collection',
    'festive pokemon card binder',
    'alolan pokemon cards',
    'galarian pokemon cards',
    'hisuian pokemon cards',
    'regional variant pokemon collection',
    'pseudo legendary pokemon cards',
    'pseudo legendary collection',
    '600 bst pokemon cards',
    'dragonite garchomp tyranitar cards',
    'pink binder pokemon',
    'pokemon card streamer',
  ],
} as const
